### ISSUE TITLE
CELL does not get parsed on recent Thunderbird Address books

### ISSUE THREAD

**Issue by tbrandt77** [ibauersachs/jmork#1]
In newer Thunderbird address books the CELL entities does not get parsed. Attached find a sample MAB file for testing.

Hint: remove .png extensio to get the .mab file.

![abook mab](https://cloud.githubusercontent.com/assets/615552/10267473/403e88b6-6a96-11e5-900f-74d65a6c0460.png)

**Comment by ibauersachs** [comment]
I tried your mab but I can't find a problem with it. After adding it in Jitsi (2.9.5475) I can search for contacts and they show up as expected. Standalone parsing also works. Can you please post the entire stacktrace you get (along with the exact .mab)?

**Comment by tbrandt77** [comment]
The book.mab is the one from, my last attachment. Here is the stacktrac I get:

Exception in thread "JAM-ThunderbirdSync-Thread-(non-deamon)" java.lang.RuntimeException: Unimplemented event: CELL
	at mork.MorkDocument.onEvent(MorkDocument.java:79)
	at mork.MorkParser.fireEvent(MorkParser.java:73)
	at mork.MorkParser.parseCell(MorkParser.java:334)
	at mork.MorkParser.parseMain(MorkParser.java:161)
	at mork.MorkParser.parse(MorkParser.java:131)
	at mork.MorkDocument.<init>(MorkDocument.java:36

**Comment by ibauersachs** [comment]
This stacktrace doesn't match the current source. Whatever JAM-ThunderbirdSync is must be using an old version.

**Comment by tbrandt77** [comment]
That's the point, man! With the latest sources it works fine. Thanx!
